---
title: "Shiny workshop"
author: "Aurora & Lene"
date: "2019-02-04"
output:
  xaringan::moon_reader:
    css: ["default", "rladies", "rladies-fonts"]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

# Let's make a shiny dashboard!

Intro to shiny?

---

#Setup:

If you don't already have the packages:

```{r, eval = F}
install.packages('shiny')
install.packages('shinydashboard')
install.packages('gapminder')
```

---

# Starter code
- https://rstudio.github.io/shinydashboard/get_started.html or
- https://github.com/rladies/meetup-presentations_oslo -> shiny-workshop/starter_kit

```{r, eval = F}
library(shiny)
library(shinydashboard)

# User interface:
ui <- dashboardPage(
  dashboardHeader(),
  dashboardSidebar(),
  dashboardBody()
)

# R code goes here:
server <- function(input, output) {
  
}

# Run the application 
shinyApp(ui = ui, server = server)
```


---

# Make it pretty using CSS

Create a new file custom.css under www:
```{css}
.skin-purple .main-header .navbar {background-color: #88398a;}      
.skin-purple .main-header .logo {background-color: #88398a;}
.skin-purple .main-header .logo:hover {background-color: #88398a;}
```


Include it in your app under dashboardBody
```{r, eval = F}
dashboardBody(
  includeCSS("www/custom.css"),
  ...
```


---


# New stuff?

```{r, eval = F}
#install.packages('colourpicker')
#install.packages('googleVis')
#install.packages('plotly')
```

---

# Resources

- https://shiny.rstudio.com
- https://rstudio.github.io/shinydashboard/
